bot:
    token: '<BOT_TOKEN>'
commandPrefix: '!'
applyRolesEmbeds:
    registerLanguage:
        title: Hello!
        description: |
            ğŸ‡ºğŸ‡¸ Welcome! Please select **only one** language and click the â˜‘ï¸.
            ğŸ‡¯ğŸ‡µ ã‚ˆã†ã“ãï¼**1ã¤ã ã‘**ã®è¨€èªã‚’é¸æŠã—ã€â˜‘ï¸ã‚’ã‚¯ãƒªãƒƒã‚¯ã—ã¦ãã ã•ã„ã€‚
            ğŸ‡¨ğŸ‡³ æ¬¢è¿ï¼è¯·é€‰æ‹©**ä»…ä¸€ç§**è¯­è¨€ï¼Œç„¶åå•å‡»â˜‘ï¸ã€‚
            ğŸ‡¹ğŸ‡¼ æ­¡è¿ï¼ è«‹é¸æ“‡**åƒ…ä¸€ç¨®**èªè¨€ï¼Œç„¶å¾Œå–®æ“Šâ˜‘ï¸ã€‚
        reactions:
            ğŸ‡ºğŸ‡¸:
                role: '<ROLD_ID>'
            ğŸ‡¯ğŸ‡µ:
                role: '<ROLD_ID>'
            ğŸ‡¨ğŸ‡³:
                role: '<ROLD_ID>'
            ğŸ‡¹ğŸ‡¼:
                role: '<ROLD_ID>'
            â˜‘ï¸:
                role: '<ROLD_ID>'
assignRoleChannels:
    '<CHANNEL_ID>':
        roleId: '<ROLD_ID>'
        leaveCommand: leave
roleLanguages:
    '<ROLD_ID>': en
    '<ROLD_ID>': ja-JP
    '<ROLD_ID>': zh-Hans
    '<ROLD_ID>': zh-Hant
